language: node_js
node_js:
- "4"
branches:
  only:
  - dev
env:
  global:
    secure: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvk6q4V0VEvhWiTnWohpw TmB/Gxi9XT44Z0sxnnehtx4AqHMdGLszlpkEKpDrZ807VuUWAFZyDRnxtCzn09mI QBDHzmUkLJpHBRK1+yo1zZxjPQFRGDm1eWj3bthnARPu+2RLQ6AXeYoxa+dKeJYR nGDmSwQgaQKyjfs5duHdU7cPRo4E48ayImPzbMuA590si3M0B0whYyA5Ze2+w/LG GlVmPeSarEOER407YlhY8+Q8n1eTec2OZGnseQVZ8YQtkmPNIzHVaO4cEHUMjd+Z P6JoQIiMKZ/VMmMs6Hqa7ae4WxR/2ts+wYwW2YIFaK7gcDC/cw2NcC5a/sAB4Osj hqKDuDKGS6kaf9iQWAmz7L/LoSnS7BnA6JriGBMSiw9Wkav90nuIbAMGOrphZmJ6 333HqI5S9c53x2Gwk0ZXwCprcF8PC2LVYExAudYCuOKVaKfCI4/tfH3yMksw2wqp YU8BWesAXV49pSe42KXw27n2ijoFC9A9ePrnv8h7FaIoeSmtcSNvhhrNrVkSOaZE IjRJxf8JuHRM39JtmnmxbkWu51nPDFHujh1mEBD0W6h6f0lVgxCsmvxNP1VZmF3k D/U4JMX/L8zBjxpkFmIArfKto4LBPdTxeFLDXVS+0NM8o48zi6Hnl2IgBsmBeCy7 ss2ui7Tv0qa/69Yu1fn2s/sCAwEAAQ==
before_install:
- export TZ='Asia/Shanghai'
- npm install -g hexo
- npm install -g hexo-cli
before_script:
#
- git config --global user.name "zenhill"
- git config --global user.email "kenjilee81460@gmail.com"
# github
- sed -i'' "s~git@github.com:zenhill/zenhill.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/zenhill/zenhill.github.io.git~" _config.yml
#
install:
- npm install
#
script:
- hexo clean
- hexo generate
#
after_success:
- hexo deploy